name = "Ntfy"
uuid = "c3f3ecf3-19bc-4a36-8a68-efc7dc2c4e18"
authors = []
version = "0.1.0"

[compat]
julia = "1.12"

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[weakdeps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[extensions]
MarkdownExt = "Markdown"

[workspace]
projects = ["test"]
