name = "Ntfy"
uuid = "c3f3ecf3-19bc-4a36-8a68-efc7dc2c4e18"
version = "0.1.0"
authors = []

[workspace]
projects = ["test"]

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
OteraEngine = "b2d7f28f-acd6-4007-8b26-bc27716e5513"
StringTemplates = "59c22e0c-4e04-425f-9782-11a552c58a8d"

[extensions]
DatesExt = "Dates"
MarkdownExt = "Markdown"
MustacheExt = "Mustache"
OteraEngineExt = "OteraEngine"
StringTemplatesExt = "StringTemplates"

[compat]
Mustache = "1.0"
OteraEngine = "1.1"
Preferences = "1.5.1"
Printf = "1.11.0"
StringTemplates = "0.1"
julia = "1.12"
