name = "Ntfy"
uuid = "c3f3ecf3-19bc-4a36-8a68-efc7dc2c4e18"
version = "0.1.0"
authors = []

[workspace]
projects = ["test"]

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"

[extensions]
DatesExt = "Dates"
MarkdownExt = "Markdown"

[compat]
Preferences = "1.5.1"
Printf = "1.11.0"
julia = "1.12"
